'use client'

import { useEffect, useRef } from 'react'
import JsBarcode from 'jsbarcode'

interface LabelBarcodeProps {
  serial: string
  // Final rendered dimensions on the label. Use inches so the bars print
  // at exactly the same width whether the user prints at 100% or via the
  // browser print dialog scaled to fit.
  widthIn: number
  heightIn: number
}

/**
 * Code128 barcode for thermal-label printing.
 * The SVG is generated by JsBarcode and then scaled via CSS to the requested
 * physical inches, so the bars print at predictable physical width.
 */
export function LabelBarcode({ serial, widthIn, heightIn }: LabelBarcodeProps) {
  const ref = useRef<SVGSVGElement>(null)

  useEffect(() => {
    if (!ref.current) return
    JsBarcode(ref.current, serial, {
      format: 'CODE128',
      displayValue: false,
      margin: 0,
      // Internal SVG units — the CSS size below scales it to physical inches.
      height: 60,
      width: 2,
    })
  }, [serial])

  return (
    <svg
      ref={ref}
      style={{
        width: `${widthIn}in`,
        height: `${heightIn}in`,
        display: 'block',
      }}
      preserveAspectRatio="none"
    />
  )
}
